# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IHabit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IHabit
  pod 'SwiftLint'
  pod 'Alamofire', '~> 5.4'

  target 'IHabitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IHabitUITests' do
    # Pods for testing
  end

end
